version: 2

builds:
  - id: kaddons
    main: ./cmd/kaddons
    binary: kaddons
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

release:
  mode: keep-existing

changelog:
  disable: true

brews:
  - name: kaddons
    repository:
      owner: qbandev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: github-actions[bot]
      email: github-actions[bot]@users.noreply.github.com
    homepage: "https://github.com/qbandev/kaddons"
    description: "Kubernetes addon compatibility checker powered by Gemini AI"
    license: "MIT"
    directory: Formula
    dependencies:
      - name: kubernetes-cli
    test: |
      system "#{bin}/kaddons --version"
    install: |
      bin.install "kaddons"
